title: Leslie Lai

author: Leslie Lai

description: Leslie Lai,front end developer,writing mostly about CSS and JavaScript(赖灿荣，前端开发者，主要撰写关于CSS和JavaScript的文章)

baseurl: ""
url: "https://lcr.github.io"

permalink: /:title/

paginate: 5
paginate_path: "/page:num/"

#reset post's layout to post
#OR: every post yaml [layout：post]
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

excerpt_separator: "<!-- more -->"

markdown: kramdown

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - index.html
  - archive.html

algolia:
  algolia_api_key: 2c3e03751f5b259ae833fe039896ad2e
  application_id:  4X0L5EZUHF
  index_name:      jekyll

# Google Analytics
google_analytics: UA-107157614-1

plugins:
  - jekyll-sitemap